# Jekyll
markdown: rdiscount
highlighter: "pygments"
permalink: /:title.html

# Conference info
conf:
  name: "Google I/O '15 Extended Aracaju"
  description: "Participe do Google I/O junto com o GDG Aracaju"
  date: "28 e 29 de maio"
  price: "Gratuito"
  address: ""
  venue: ""
  city: "Aracaju"

# Site info
site:
  url: "http://io.gdgaracaju.com.br"
  favicon: "http://site.gdgaracaju.com.br/favicon.png"
  googleanalytics: "UA-49492619-1"
  images:
    cover: "http://io.gdgaracaju.com.br/img/cover.png"
    facebook: "http://io.gdgaracaju.com.br/img/cover.png"

subscribe_text: "Inscreva-se no evento!"
subscribe_url: "https://goo.gl/2f6MzS"

# Active sections on the website
sections:
  about: true
  c4p: false
  location: false
  speakers: false
  schedule: true
  sponsors: false
  partners: true
  contact: true

# The entire schedule
schedule:
  -
    name: "Entrada: Dia 1"
    time: "28/05 13:00"
  -
    name: "Sundar Pichai"
    photo: "img/sundar-pichai.jpg"
    bio: ""
    company: "Google"
    twitter: ""
    presentation:
      title: "Keynote"
      description: "Ao vivo de San Francisco, junte-se a nós e descubra as inovações das plataformas e produtos Google."
      time: "28/05 13:30"
  -
    name: "Chet Haase e Dan Sandler"
    photo: "img/io.png"
    bio: ""
    company: "Google"
    twitter: ""
    presentation:
      title: "What's new in Android"
      description: "Ao vivo de San Francisco, nesta sessão serão destacadas as novas features para desenvolvedores da plataforma Android."
      time: "28/05 17:00"
  -
    name: "Jamal Eason, Tor Norbye e Xavier Ducrochet"
    photo: "img/io.png"
    bio: ""
    company: "Google"
    twitter: ""
    presentation:
      title: "What's news in Android Development Tools"
      description: "Ao vivo de San Francisco, esta sessão irá prover um tour profundo nas ferramentas de desenvolvimento Android e um tudo que há de novo, com dicas e truques para extrair o máximo delas!"
      time: "28/05 18:00"
  -
    name: "Ítalo Marcel"
    photo: "img/italo-marcel.jpg"
    bio: "Um gamer nato e apaixonado por Android, formado em Programação de Sistemas pelo Instituto Federal de Sergipe e graduando em Ciência da Computação pela Universidade Federal de Sergipe. Programa desde os 15 anos de idade, e já desenvolveu diversos aplicativos durante os mais de 4 anos como engenheiro Android. Inovar faz parte de seu DNA."
    company: "Getinfo"
    twitter: ""
    presentation:
      title: "Desmistificando Gradle"
      description: ""
      time: "28/05 19:00"

# List of Sponsors
sponsors:
  -
    name: "Eventick"
    logo: "http://f.cl.ly/items/1U3p0Z0e2w0I1i3z1X22/Image%202012.09.25%203:00:58%20PM.png"
    url: "http://eventick.com.br"

# List of Partners
partners:
  -
    name: "BrazilJS"
    logo: "http://f.cl.ly/items/2N3i2W0X2f3c2g2Z2N0f/Untitled-1.png"
    url: "http://braziljs.org"

# About section
about_section:
   title: "O que é o Google I/O?"
   description: 
    - 
      p: "Google I/O é um evento anual de tecnologia que acontece na sede do Google na Califórnia e simultaneamente em mais de 600 lugares em 90 países do mundo todo, através dos eventos I/O Extended.  O objetivo é fomentar o empreendedorismo digital, a economia criativa e a inovação tecnológica. Buscamos promover o ativismo digital, o engajamento e a colaboração, visando a disseminação desses valores em nossa região."

# Call for papers section
c4p_section:
   title: "Call for papers"
   text: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat."
   c4p_url: "http://call4paperz.com"
   c4p_caption: "Submit"
   c4p_rules_url: "http://call4paperz.com"
   c4p_rules_caption: "Read the rules."

# Contact section
contact_section:
   title: "Contato"
   text: "Fale conosco se tiver qualquer dúvida!"
   contacts:
   -
     title: "Email"
     link: "mailto:gdgaracaju@gmail.com"
   -
     title: "Google+"
     link: "https://plus.google.com/communities/100418157558568471841"
   email: "gdgaracaju@gmail.com"
   twitter_url: "http://twitter.com/gdgaracaju"
   twitter_username: "@gdgaracaju"
   show_form: false
   form:
    action: "contato.php"
    name: "What's your name?"
    email: "What's your email?"
    message: "Write a message"
    send_button: "Send"

# Location section
location_section:
   title: "Local"

# Partners section
partners_section:
   title: "Parceiros"
   show_your_logo_here: false
   your_logo_here_link: "mailto:gdgaracaju@gmail.com"

partners:
  -
    name: "CajuValley"
    logo: "./img/partners/cajuvalley.png"
    url: "https://www.facebook.com/cajuvalley"
  -
    name: "CEC"
    logo: "./img/partners/cec.png"
    url: "http://www.cecaracaju.com.br/coworking/"
  -
    name: "FANESE"
    logo: "./img/partners/fanese.png"
    url: "http://www.fanese.edu.br/"
  -
    name: "Getinfo"
    logo: "./img/partners/getinfo.png"
    url: "http://getinfo.net.br/"
  -
    name: "GDG Aracaju"
    logo: "./img/partners/gdgaracaju.png"
    url: "http://www.gdgaracaju.com.br/"
  -
    name: "DP Sistemas"
    logo: "./img/partners/dpsistemas.png"
    url: "http://www2.dpsistemas.com.br/"
  -
    name: "Popcode"
    logo: "./img/partners/popcode.jpg"
    url: "http://www.popcode.com.br/"
  -
    name: "Rede+"
    logo: "./img/partners/redemais.png"
    url: "http://gruporedemais.com/"
  -
    name: "SergipeTec"
    logo: "./img/partners/sergipetec.png"
    url: "http://www.sergipetec.se.gov.br/"


# Schedule section
schedule_section:
   title: "Agenda"
   text: ""
   time: "Hora"
   slot: "Sessão"
   description: "Descrição"

# Speakers section
speakers_section:
   title: "Palestrantes"

# Sponsors section
sponsors_section:
   title: "Patrocinadores"
   show_your_logo_here: true